# Site settings
title: SPY vs CAT5
description: "Club de hacking de l'université Laval"
baseurl: "" # the subpath of your site
url: "http://hacking.fsg.ulaval.ca/" 
#url: https://spyvscat5.github.io

# User settings
username: SPY vs CAT5
user_title: SPY vs CAT5
email: clubhacking@fsg.ulaval.ca
github_username:  SpyVsCat5
youtube_username:  UCqHR0icKT20KwFDjaZuFt7?sub_confirmation=1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
future: true


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: Accueil
    url: /
  - title: À propos
    url: /about
  - title: Laboratoire
    url: /laboratory
  - title: Nous joindre
    url: /contact
  - title: Premiers pas
    url: /starterkit
  - title: Événements
    url: /events

# projects in header index
projects:
  - name: Workshops / Présentations
    url: https://github.com/SpyVsCat5/Workshops
  - name: Outils de CTF
    url: https://github.com/SpyVsCat5/Outils-CTF
  - name: Liste de livres
    url: https://github.com/SpyVsCat5/Book-List

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
